apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: github-hpa-test
spec:
  minReplicas: 1  # 최소 replicas 개수
  maxReplicas: 5  # 최대 replicas 개수
  metrics:
  - resource:
      name: cpu  # HPA를 구성할 리소스(CPU, MEM 등)
      targetAverageUtilization: 30  # CPU 사용률이 30% 이상일 경우 생성
    type: Resource  # 리소스 타입 선언
  scaleTargetRef:  # 스케일 아웃할 타겟 설정
    apiVersion: apps/v1
    kind: Deployment  #  스케일 아웃할 타겟의 종류 (deployment, replicaset 등)
    name: devops-spring-deployment  #  스케일 아웃할 타겟의 네임
